name: fintrack
description: "Projeto mobile em Flutter voltado ao controle financeiro pessoal, com foco em usabilidade, organização de gastos e visualização clara do saldo."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo/
