// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static FirebaseOptions get web => FirebaseOptions(
      apiKey: _webApiKey,
    appId: '1:871116334001:web:5b07b4f90a07ceeb6e5390',
    messagingSenderId: '871116334001',
    projectId: 'fintrack-dev-4e043',
    authDomain: 'fintrack-dev-4e043.firebaseapp.com',
    storageBucket: 'fintrack-dev-4e043.firebasestorage.app',
  );

    static FirebaseOptions get android => FirebaseOptions(
      apiKey: _androidApiKey,
    appId: '1:871116334001:android:693c11bdd654846f6e5390',
    messagingSenderId: '871116334001',
    projectId: 'fintrack-dev-4e043',
    storageBucket: 'fintrack-dev-4e043.firebasestorage.app',
  );

    static FirebaseOptions get ios => FirebaseOptions(
      apiKey: _appleApiKey,
    appId: '1:871116334001:ios:4b54663f94a4b9766e5390',
    messagingSenderId: '871116334001',
    projectId: 'fintrack-dev-4e043',
    storageBucket: 'fintrack-dev-4e043.firebasestorage.app',
    iosBundleId: 'com.leomoraes.fintrack',
  );

    static FirebaseOptions get macos => FirebaseOptions(
      apiKey: _appleApiKey,
    appId: '1:871116334001:ios:4b54663f94a4b9766e5390',
    messagingSenderId: '871116334001',
    projectId: 'fintrack-dev-4e043',
    storageBucket: 'fintrack-dev-4e043.firebasestorage.app',
    iosBundleId: 'com.leomoraes.fintrack',
  );

    static FirebaseOptions get windows => FirebaseOptions(
      apiKey: _webApiKey,
    appId: '1:871116334001:web:5d29799ead9573e06e5390',
    messagingSenderId: '871116334001',
    projectId: 'fintrack-dev-4e043',
    authDomain: 'fintrack-dev-4e043.firebaseapp.com',
    storageBucket: 'fintrack-dev-4e043.firebasestorage.app',
  );

    static String get _webApiKey {
      const value = String.fromEnvironment('FIREBASE_WEB_API_KEY');
      return _requireValue('FIREBASE_WEB_API_KEY', value);
    }

    static String get _androidApiKey {
      const value = String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
      return _requireValue('FIREBASE_ANDROID_API_KEY', value);
    }

    static String get _appleApiKey {
      const value = String.fromEnvironment('FIREBASE_APPLE_API_KEY');
      return _requireValue('FIREBASE_APPLE_API_KEY', value);
    }

    static String _requireValue(String name, String value) {
      if (value.isEmpty) {
        throw UnsupportedError(
          'Missing Firebase configuration for $name. '
          'Provide it with --dart-define or --dart-define-from-file.',
        );
      }

      return value;
    }
}
